# Generated by Django 5.1.3 on 2025-01-04 16:41

import chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='audio',
            field=models.FileField(upload_to='audio/', validators=[chat.validators.validate_audio]),
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='video',
            field=models.FileField(upload_to='video/', validators=[chat.validators.validate_video]),
        ),
    ]
